### PR TITLE
issue 108, supporting running apiman on http too

### PR DESCRIPTION
**Pull request by KurtStam**

### CODE REVIEW

**Comment by KurtStam** [comment]
Hi @gashcrumb, please take a look. It looks up the service scheme annotation.

**Comment by gashcrumb** [comment]
Awesome!  Can you do a 'gulp build' and check in the generated hawtio-kubernetes.js also?  Thanks!

**Comment by KurtStam** [comment]
@gashcrumb done, btw the css changed too.

**Comment by gashcrumb** [comment]
Great, thanks Kurt!

**Pull request merged**
